server:
  port: 8081
  context-path: /spring-boot-Demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
