spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true